// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "colorrec.h"

/////////////////////////////////////////////////////////////////////////////
// CColorrec

IMPLEMENT_DYNCREATE(CColorrec, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CColorrec properties

long CColorrec::GetBrnum()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CColorrec::SetBrnum(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CColorrec operations

void CColorrec::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
