// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "colorbox.h"

/////////////////////////////////////////////////////////////////////////////
// CColorbox

IMPLEMENT_DYNCREATE(CColorbox, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CColorbox properties

long CColorbox::GetBrnum()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CColorbox::SetBrnum(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CColorbox operations

void CColorbox::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
