// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CColortab wrapper class

class CColortab : public CWnd
{
protected:
	DECLARE_DYNCREATE(CColortab)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xcb4a96a8, 0x611e, 0x45dc, { 0xa5, 0x1b, 0xee, 0xa0, 0xa7, 0xfd, 0xee, 0x9e } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetChoocecolor();
	void SetChoocecolor(long);
	short GetY();
	void SetY(short);
	short GetX();
	void SetX(short);

// Operations
public:
	void AboutBox();
};
