// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "colortab.h"

/////////////////////////////////////////////////////////////////////////////
// CColortab

IMPLEMENT_DYNCREATE(CColortab, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CColortab properties

long CColortab::GetChoocecolor()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CColortab::SetChoocecolor(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

short CColortab::GetY()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CColortab::SetY(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

short CColortab::GetX()
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

void CColortab::SetX(short propVal)
{
	SetProperty(0x3, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CColortab operations

void CColortab::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
